name: js_experimental
version: 0.3-dev.1
author: Dart Team <misc@dartlang.org>
description: Seamless JavaScript Interop
homepage: https://github.com/justinfagnani/js-interop
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.11.0'
