name: js_experimental
version: 0.3.0-dev.1
author: Dart Team <misc@dartlang.org>
description: Seamless JavaScript Interop
homepage: https://github.com/justinfagnani/js-interop
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  analyzer: '>=0.21.1 <0.22.0'
  barback: '>=0.11.1 <0.15.0'
  browser: '>=0.9.0 <0.11.0'
  code_transformers: '>=0.1.5 <1.0.0'
  quiver: '>= 0.18.0 <0.20.0'
dev_dependencies:
  unittest: '>=0.9.0 < 0.12.0'
environment:
  sdk: '>=1.0.0 < 2.0.0'
transformers:
- js:
    entry_points:
      - test/transformer/transformer_test.dart
      - example/interfaces/interfaces.dart
- $dart2js:
    verbose: true
    suppressWarnings: false
    suppressHints: false
    $include: test/transformer/transformer_test.dart
